icenet:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
image:
  imagePullSecret: nextlabs-registry-credentials
  pullPolicy: Always
  repository: registry.nextlabs.com/platform
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
  enabled: true
  icenet:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 500m
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    enabled: false
  tls:
    enabled: true
    secretName: null
livenessProbe:
  timeoutSeconds: 10
managementServer:
  resources:
    limits:
      cpu: 1
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 6Gi
nextlabs:
  cc:
    adminPassword: null
    commProfile:
      heartBeatFreqTime: 2
      heartBeatFreqTimeUnit: minutes
      pushEnabled: false
    db:
      password: null
      retryAttempts: 5
      url: null
      username: null
    dnsName: null
    enrolledDataVolumeClaimName: null
    icenet:
      dnsName: null
    license: null
    logsVolumeClaimName: null
    policyValidatorDataVolumeClaimName: null
    port:
      externalPort: 443
    ssl:
      cacerts:
        cert1: null
        cert2: null
        cert3: null
        cert4: null
      keyPairStore:
        certificate:
          content: null
        content: null
        keyAlias: null
        password: null
      keystore:
        password: null
      truststore:
        password: null
policyController:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
policyValidator:
  enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
readinessProbe:
  timeoutSeconds: 10
securityContext:
  fsGroup: null
  runAsUser: null
service:
  type: ClusterIP
startupProbe:
  timeoutSeconds: 10
