apiVersion: v1
kind: Secret
metadata:
  name: {{ include "control-center.fullname" . }}
  labels:
    {{- include "control-center.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  nextlabs.cc.adminPassword: {{ .Values.nextlabs.cc.adminPassword | quote }}
  nextlabs.cc.configService.password: {{ randAlphaNum 32 | quote }}
  {{- if .Values.policyValidator.enabled }}
  nextlabs.cc.policyValidator.oidcClientSecret: {{ randAlphaNum 32 | quote }}
  {{- end }}
  nextlabs.cc.ssl.keystore.password: {{ .Values.nextlabs.cc.ssl.keystore.password | quote }}
  nextlabs.cc.ssl.truststore.password: {{ .Values.nextlabs.cc.ssl.truststore.password | quote }}
  {{- include "cc.tls" . | nindent 2 }}
