apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextlabs-control-center-license
  labels:
    helm.sh/chart: {{ include "control-center.chart" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-nextlabs-control-center-license
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  nextlabs.cc.license: {{ .Values.nextlabs.cc.license | quote }}
