apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextlabs-control-center-database-details
  labels:
    helm.sh/chart: {{ include "control-center.chart" . }}
    app.kubernetes.io/name: {{ .Release.Name }}-nextlabs-control-center-database-details
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  nextlabs.cc.db.password: {{ .Values.nextlabs.cc.db.password | quote }}
  nextlabs.cc.db.url: {{ .Values.nextlabs.cc.db.url | quote }}
  nextlabs.cc.db.username: {{ .Values.nextlabs.cc.db.username | quote }}
