apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icenet.fullname" . }}
  labels:
    {{- include "icenet.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  NEXTLABS_CC_ENVIRONMENT: CONTAINER
  NEXTLABS_CC_HEALTHCHECKSERVICE_ENABLED: "true"
  NEXTLABS_CC_MANAGEMENTSERVER_HOST: {{ .Release.Name }}-nextlabs-control-center-management-server
  NEXTLABS_CC_SSL_CACERTS_0_ALIAS: control_center
  {{- if .Values.nextlabs.cc.ssl.cacerts.cert1 }}
  NEXTLABS_CC_SSL_CACERTS_1_ALIAS: cacert_1
  NEXTLABS_CC_SSL_CACERTS_1_CONTENT: {{ .Values.nextlabs.cc.ssl.cacerts.cert1 | quote }}
  {{- end }}
  {{- if .Values.nextlabs.cc.ssl.cacerts.cert2_content }}
  NEXTLABS_CC_SSL_CACERTS_2_ALIAS: cacert_2
  NEXTLABS_CC_SSL_CACERTS_2_CONTENT: {{ .Values.nextlabs.cc.ssl.cacerts.cert2_content | quote }}
  {{- end }}
  {{- if .Values.nextlabs.cc.ssl.cacerts.cert3_content }}
  NEXTLABS_CC_SSL_CACERTS_3_ALIAS: cacert_3
  NEXTLABS_CC_SSL_CACERTS_3_CONTENT: {{ .Values.nextlabs.cc.ssl.cacerts.cert3_content | quote }}
  {{- end }}
  {{- if .Values.nextlabs.cc.ssl.cacerts.cert4_content }}
  NEXTLABS_CC_SSL_CACERTS_4_ALIAS: cacert_4
  NEXTLABS_CC_SSL_CACERTS_4_CONTENT: {{ .Values.nextlabs.cc.ssl.cacerts.cert4_content | quote }}
  {{- end }}
  NEXTLABS_CC_TYPE: ICENET
  NEXTLABS_CC_WAITFOR_URL: https://{{ .Release.Name }}-nextlabs-control-center-management-server:4443/console/api/v1/system/status
