apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icenet.fullname" . }}
  labels:
    {{- include "icenet.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "icenet.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.icenet.replicas }}
  template:
    metadata:
      labels:
        {{- include "icenet.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
      securityContext:
      {{- if .Values.securityContext.runAsUser }}
      {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-{{ .Release.Name }}-i
          containerPort: 8443
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /health-check/
            port: 18080
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /health-check/
            port: 18080
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        startupProbe:
          httpGet:
            scheme: HTTPS
            path: /health-check/
            port: 18080
          failureThreshold: 60
          periodSeconds: 30
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
        resources:
          {{- toYaml .Values.icenet.resources | nindent 12 }}
        env:
        - name: NEXTLABS_CC_MANAGEMENTSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.configService.password
        - name: NEXTLABS_CC_SSL_CACERTS_0_CONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.ccKeyPairStore.certificate
        envFrom:
        - configMapRef:
            name: {{ include "icenet.fullname" . }}
        volumeMounts:
        {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
        - name: logs
          mountPath: /opt/NextLabs/PolicyServer/server/logs
        {{- end }}
      volumes:
      {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Values.nextlabs.cc.logsVolumeClaimName }}
      {{- end }}
