apiVersion: v1
kind: Service
metadata:
  name: {{ include "icenet.fullname" . }}
  labels:
    {{- include "icenet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8443
    protocol: TCP
    name: http-{{ .Release.Name }}-i
  selector:
    {{- include "icenet.selectorLabels" . | nindent 4 }}
