{{- if .Values.ingress.icenet.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "icenet.fullname" . }}
  labels:
    {{- include "icenet.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.icenet.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .Values.nextlabs.cc.icenet.dnsName | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nextlabs-control-center-icenet
            port:
              number: 8443
{{- end }}
