{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "control-center.fullname" . }}
  labels:
    {{- include "control-center.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.nextlabs.cc.dnsName | quote }}
    {{- if .Values.ingress.secretName }}
    secretName: {{ .Values.ingress.secretName }}
    {{- else }}
    secretName: {{ .Release.Name }}-nextlabs-control-center-ingress-tls
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.nextlabs.cc.dnsName | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nextlabs-control-center-management-server
            port:
              number: 4443
      {{- if .Values.policyValidator.enabled }}
      - path: /policy-validator
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nextlabs-policy-validator
            port:
              number: 8443
      {{- end }}
      - path: /dpc
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nextlabs-policy-controller-java
            port:
              number: 8443
{{- end }}
