{{- if .Values.ingress.enabled -}}
{{- if not .Values.ingress.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextlabs-control-center-ingress-tls
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}-nextlabs-control-center-ingress-tls
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": pre-install
type: kubernetes.io/tls
data:
  {{- include "cc.ingress.tls" . | nindent 2 }}
{{- end }}
{{- end }}
