apiVersion: v1
kind: Service
metadata:
  name: {{ include "management-server.fullname" . }}
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 4443
    protocol: TCP
    name: http-{{ .Release.Name }}-a
  - port: 7443
    protocol: TCP
    name: http-{{ .Release.Name }}-c
  - port: 8443
    protocol: TCP
    name: http-{{ .Release.Name }}-w
  - port: 61616
    protocol: TCP
    name: http-{{ .Release.Name }}-q
  selector:
    {{- include "management-server.selectorLabels" . | nindent 4 }}
