apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "management-server.fullname" . }}
  labels:
    {{- include "management-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "management-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "management-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
      securityContext:
      {{- if .Values.securityContext.runAsUser }}
      {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - {{ .Release.Name }}-nextlabs-control-center-management-server
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-{{ .Release.Name }}-a
          containerPort: 4443
          protocol: TCP
        - name: http-{{ .Release.Name }}-c
          containerPort: 7443
          protocol: TCP
        - name: http-{{ .Release.Name }}-w
          containerPort: 8443
          protocol: TCP
        - name: http-{{ .Release.Name }}-q
          containerPort: 61616
          protocol: TCP
        resources:
          {{- toYaml .Values.managementServer.resources | nindent 12 }}
        env:
        - name: NEXTLABS_CC_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.adminPassword
        - name: NEXTLABS_CC_DB_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-nextlabs-control-center-database-details
              key: nextlabs.cc.db.url
        - name: NEXTLABS_CC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-nextlabs-control-center-database-details
              key: nextlabs.cc.db.username
        - name: NEXTLABS_CC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-nextlabs-control-center-database-details
              key: nextlabs.cc.db.password
        - name: NEXTLABS_CC_MANAGEMENTSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.configService.password
        - name: NEXTLABS_CC_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.keystore.password
        - name: NEXTLABS_CC_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.truststore.password
        - name: NEXTLABS_CC_SSL_CACERTS_0_CONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.ccKeyPairStore.certificate
        - name: NEXTLABS_CC_SSL_CCKEYPAIRSTORE_KEYCONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.ccKeyPairStore.key
        - name: NEXTLABS_CC_SSL_CCKEYPAIRSTORE_CERTIFICATECONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.ccKeyPairStore.certificate
        - name: NEXTLABS_CC_SSL_WEBKEYPAIRSTORE_KEYCONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.webKeyPairStore.key
        - name: NEXTLABS_CC_SSL_WEBKEYPAIRSTORE_CERTIFICATECONTENT
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.ssl.webKeyPairStore.certificate
        - name: NEXTLABS_CC_LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-nextlabs-control-center-license
              key: nextlabs.cc.license
        {{- if .Values.policyValidator.enabled }}
        - name: NEXTLABS_CC_APPLICATION_CCOIDCCONFIG_SERVICES_0_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.cc.policyValidator.oidcClientSecret
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "management-server.fullname" . }}
        volumeMounts:
        {{- if .Values.nextlabs.cc.enrolledDataVolumeClaimName }}
        - name: enrollment-data
          mountPath: /opt/NextLabs/PolicyServer/tools/enrollment/data
        {{- end }}
        {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
        - name: logs
          mountPath: /opt/NextLabs/PolicyServer/server/logs
        {{- end }}
      volumes:
      {{- if .Values.nextlabs.cc.enrolledDataVolumeClaimName }}
      - name: enrollment-data
        persistentVolumeClaim:
          claimName: {{ .Values.nextlabs.cc.enrolledDataVolumeClaimName }}
      {{- end }}
      {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Values.nextlabs.cc.logsVolumeClaimName }}
      {{- end }}
