apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "policy-controller-java.fullname" . }}
  labels:
    {{- include "policy-controller-java.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "policy-controller-java.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.policyController.replicas }}
  template:
    metadata:
      labels:
        {{- include "policy-controller-java.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}
      {{- end }}
      securityContext:
      {{- if .Values.securityContext.runAsUser }}
      {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/nextlabs-policy-controller-java:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http-{{ .Release.Name }}-p
          containerPort: 8443
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8443
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        readinessProbe:
          tcpSocket:
            port: 8443
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        startupProbe:
          tcpSocket:
            port: 8443
          failureThreshold: 60
          periodSeconds: 30
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
        resources:
          {{- toYaml .Values.policyController.resources | nindent 12 }}
        envFrom:
        - configMapRef:
            name: {{ include "policy-controller-java.fullname" . }}
        env:
        - name: NEXTLABS_JPC_TLS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.jpc.tls.key
        - name: NEXTLABS_JPC_TLS_CERTIFICATE
          valueFrom:
            secretKeyRef:
              name: {{ include "control-center.fullname" . }}
              key: nextlabs.jpc.tls.certificate
        volumeMounts:
        {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
        - name: logs
          mountPath: /usr/share/apache-tomcat/nextlabs/logs
        - name: logs
          mountPath: /usr/share/apache-tomcat/logs
        {{- end }}
      volumes:
      {{- if .Values.nextlabs.cc.logsVolumeClaimName }}
      - name: logs
        persistentVolumeClaim:
          claimName: {{ .Values.nextlabs.cc.logsVolumeClaimName }}
      {{- end }}