apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "policy-controller-java.fullname" . }}
  labels:
    {{- include "policy-controller-java.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  JAVA_OPTS: -Dnextlabs.support.xacml.policies=true -Dnextlabs.error.result.acceptable=true -Dnextlabs.dont.care.acceptable=true
  NEXTLABS_JPC_ENABLE_RMI: "false"
  NEXTLABS_JPC_HOST: {{ .Release.Name }}-nextlabs-policy-controller-java
  NEXTLABS_JPC_ICENET_HOST: {{ .Release.Name }}-nextlabs-control-center-icenet
  NEXTLABS_JPC_ICENET_PORT: "8443"
  NEXTLABS_JPC_PORT: "8443"
  NEXTLABS_JPC_DEBUG_LOGGING: "true"
  NEXTLABS_JPC_TEMP_AGENT_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1FRUNBUUF3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRUp6QWxBZ0VCQkNCU1I4WE04NHZicHhIZVNFT2UKdkIvekxnN3MrWmowQmJRTXlsOUp2SmN1akE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQ1RDQ0FheWdBd0lCQWdJRGFZb1NNQXdHQ0NxR1NNNDlCQU1DQlFBd2VURUxNQWtHQTFVRUJoTUNWVk14CkN6QUpCZ05WQkFnVEFrTkJNUkl3RUFZRFZRUUhFd2xUWVc0Z1RXRjBaVzh4RVRBUEJnTlZCQW9UQ0U1bGVIUk0KWVdKek1Sd3dHZ1lEVlFRTEV4TkRiMjF3YkdsaGJuUkZiblJsY25CeWFYTmxNUmd3RmdZRFZRUURFdzlVWlcxdwpiM0poY25rZ1FXZGxiblF3SGhjTk1UY3dNVEU1TVRneE1ETXlXaGNOTWpjd01URTNNVGd4TURNeVdqQjVNUXN3CkNRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNCTUNRMEV4RWpBUUJnTlZCQWNUQ1ZOaGJpQk5ZWFJsYnpFUk1BOEcKQTFVRUNoTUlUbVY0ZEV4aFluTXhIREFhQmdOVkJBc1RFME52YlhCc2FXRnVkRVZ1ZEdWeWNISnBjMlV4R0RBVwpCZ05WQkFNVEQxUmxiWEJ2Y21GeWVTQkJaMlZ1ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBCkJERTBQeTQrdVZGRjUrUXdqSml6UlR5ZmlLZi8xVmxRN2dGYlkyc090VkRodXVyU09ObkR5QXRqU0trS0ZJdTkKTlFjaHZRN1o2RlNNV0JJTFlESSt2VnlqSVRBZk1CMEdBMVVkRGdRV0JCU0Q1RUI1K1g1a3c5Szd4U0tpRzAvQworVEJpSkRBTUJnZ3Foa2pPUFFRREFnVUFBMGtBTUVZQ0lRRG1IYllHeS9xQVhhMkZPbGNpd0lpWDhCM0VxTE0yCmVVVDJBT1IxMG5mWG1RSWhBSjZraFFiK05MazdvUU44THpvZHhkUEMyeERzRjE4QTBUYWF4K05tMXJDKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==