apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-controller-java.fullname" . }}
  labels:
    {{- include "policy-controller-java.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8443
    protocol: TCP
    name: http-{{ .Release.Name }}-p
  selector:
    {{- include "policy-controller-java.selectorLabels" . | nindent 4 }}
